Sprint 04
Pirozoni/MovieQuiz pull request #1
Opened 2024-08-25 20:02 UTC by Pirozoni

Привет ревьюер, это был долгий путь.
Спасибо за твой обзор.

2024-08-26 07:22 UTC, Kirchberg commented on MovieQuiz/Helpers/UIColor+Extensions.swift
> +//    }
Лишние строки кода было бы хорошо удалять. [Про проблемы лишних строк кода можно найти информацию в этой статье](https://habr.com/ru/articles/354750/)

2024-08-26 07:24 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +}
Модели данных необходимо поместить внутри `MovieQuizViewController` и для каждой из них добавить модификатор доступа `private`

2024-08-26 07:28 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Отлично, что ты используешь `MARK` в коде — это действительно помогает быстро находить нужные участки с помощью Xcode Minimap. Если у тебя есть пустые секции, лучше их удалить и добавить позже, когда появится необходимость. Так код будет выглядеть аккуратнее. Молодец, так держать!

2024-08-26 07:29 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    // MARK: - IB Outlets
Отступ после `MARK` помогает улучшить читаемость кода. Он визуально разделяет секции и делает структуру проекта более чистой

2024-08-26 07:35 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    // метод конвертации, который принимает моковый вопрос и возвращает вью модель для экрана вопроса
Хотел бы отметить, что в данном файле встречается много комментариев. Документирование кода – это важная и полезная практика, но лучше избегать комментариев, если их смысл уже выражен через название функции или переменной. Как писал Роберт Мартин, хороший код должен быть самодокументируемым, чтобы его было легко понять без лишних пояснений, но если это не получается, то хорошо было бы добавить комментарий. [Ссылка на статью про комментирование кода](https://habr.com/ru/companies/piter/articles/458990/)

2024-08-26 07:40 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            let firstQuestion = self.questions[self.currentQuestionIndex]
Для размышлений: в этой строчке кода мы обращаемся к массиву `questions` по индексу `currentQuestionIndex`. Однако, если индекс окажется за пределами массива (например, будет больше количества элементов или отрицательным), приложение может завершиться с ошибкой в RunTime. Чтобы избежать этой ситуации, можно использовать безопасное извлечение элемента из массива. Для этого в проекте есть файл `Array+Extensions`, где реализован безопасный subscript. Это позволит избежать падения приложения, если `currentQuestionIndex` выходит за пределы массива.

2024-08-26 07:50 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            preferredStyle: .alert)
Для более аккуратных отступов можно оформить код так:
```swift
let alert = UIAlertController(
    title: result.title,
    message: result.text,
    preferredStyle: .alert
)
```
Так код будет выглядеть проще для восприятия и легче для последующего редактирования, если будет добавлен новый параметр

2024-08-26 07:56 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private weak var yesButton: UIButton!
В данном случае `weak` не требуется, потому что `IBOutlet` переменные относятся к UI-элементам, которые находятся в иерархии `MovieQuizViewController` и добавлены через Interface Builder. Эти элементы уже находятся под управлением контроллера, который создает их и удерживает сильную ссылку на них

2024-08-26 08:01 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
В данном случае нет необходимости использовать `== true` в условии. Булево значение само по себе уже представляет логическое утверждение. 
Проще и читаемее будет написать условие так:
```swift
if isCorrect {
    correctAnswers += 1
}
```
Здесь `if isCorrect` автоматически проверяет, истинно ли значение `isCorrect`. Это позволяет сократить код, если бы были слишком много проверок.

2024-08-26 08:02 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
По условию задания необходимо выставить задержку в 1 секунду

2024-08-26 08:02 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
🔥 Добавлена блокировка кнопок на время показа правильного ответа, молодец!

2024-08-26 08:18 UTC, Kirchberg requested changes
Привет, Надежда!
Спасибо за тёплые слова в начале пул-реквеста! ❤️ Ты проделала отличную работу — всё выглядит аккуратно и грамотно. Однако есть несколько критических моментов, которые нужно поправить, прежде чем я смогу принять твою работу. Не переживай, их немного. Жду твоего апдейта! :)

2024-08-30 11:04 UTC, Pirozoni commented
Спасибо за такой подробный и теплый разбор!
Постаралась пофиксить всё по пунктикам, но насчет пункта с решением через Array+Extensions не совсем поняла, поэтому добавила guard для безопасного запуска.

2024-08-30 12:51 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        guard let currentQuizQuestion = questions[safe: currentQuestionIndex] else { return }
✨

2024-08-30 12:52 UTC, Kirchberg commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +//        let currentQuestion = questions[currentQuestionIndex]
Было бы хорошо удалить

2024-08-30 12:58 UTC, Kirchberg approved these changes
Критических моментов больше нет, Approve ✨

2024-10-03 19:29 UTC, merged